# -*- coding: utf-8 -*-
"""584_Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JECEnhWEMyhTKQaeP2PCWo4Fa3tZlnR2
"""

import pandas as pd
import numpy as np
from sklearn import  tree

dataset = pd.read_csv("./Train.csv")

dataset.isnull().sum()

one_hot_train = pd.get_dummies(dataset[['F10', 'F11']])
train_ = pd.concat([dataset['F1'],dataset['F2'] ,dataset['F3'], dataset['F4'],dataset['F5'], dataset['F6'] ,dataset['F7'], dataset['F8'], dataset['F9'], one_hot_train], axis =1)

credit_0 = dataset[dataset['credit']==0]
credit_1 =  dataset[dataset['credit']==1]
print((len(credit_1)/ len(dataset))*100)
print((len(credit_0)/ len(dataset))*100)

classifier = tree.DecisionTreeClassifier(max_depth= 20, min_samples_split = 45, class_weight = {0:0.2408 , 1:0.7591})

classifier_train=classifier.fit(train_, dataset['credit'])

test_data = pd.read_csv("./Test.csv")

one_hot_test = pd.get_dummies(test_data[['F10', 'F11']])
test_ = pd.concat([test_data['F1'],test_data['F2'] ,test_data['F3'], test_data['F4'],test_data['F5'], test_data['F6'] ,test_data['F7'], test_data['F8'], test_data['F9'], one_hot_test], axis =1)

output=classifier.predict(test_)

output=output.reshape(output.size,1)

a_file = open("output.txt", "w")
for row in output:
    # np.savetxt(a_file, row)
    a_file.write(str(row[0])+"\n")

a_file.close()