# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tS6eo_QAqnykf06eTH5jZ7cAz_xgYfQq
"""

import pandas as pd
import numpy as np
from sklearn import  tree
import pydotplus
from IPython.display import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

dataset = pd.read_csv("./Train.csv")

one_hot_train = pd.get_dummies(dataset[['F10', 'F11']]) 
train_ = pd.concat([dataset['F1'],dataset['F2'] ,dataset['F3'], dataset['F4'],dataset['F5'], dataset['F6'] ,dataset['F7'], dataset['F8'], dataset['F9'], one_hot_train], axis =1)

random_classifier = RandomForestClassifier(n_estimators= 500)
random_classifier = random_classifier.fit(train_, dataset['credit'])

test_data = pd.read_csv("./Test.csv")

one_hot_test = pd.get_dummies(test_data[['F10', 'F11']])
test_ = pd.concat([test_data['F1'],test_data['F2'],test_data['F3'], test_data['F4'],test_data['F5'],test_data['F6'],test_data['F7'], test_data['F8'], test_data['F9'], one_hot_test], axis =1)
y_pred =random_classifier.predict(test_)

output=y_pred.reshape(y_pred.size,1)

a_file = open("output.txt", "w")
for row in output:
    # np.savetxt(a_file, row)
    a_file.write(str(row[0])+"\n")

a_file.close()

